export const FloorLayout = {
    LAYOUT_LARGE: 0,
    LAYOUT_SMALL: 1,
    LAYOUT_ONE_ROOM_MONSTER_HOUSE: 2,
    LAYOUT_OUTER_RING: 3,
    LAYOUT_CROSSROADS: 4,
    LAYOUT_TWO_ROOMS_WITH_MONSTER_HOUSE: 5,
    LAYOUT_LINE: 6,
    LAYOUT_CROSS: 7,
    LAYOUT_LARGE_0x8: 8,
    LAYOUT_BEETLE: 9,
    LAYOUT_OUTER_ROOMS: 10,
    LAYOUT_MEDIUM: 11,
    LAYOUT_UNUSED_0xC: 12,
    LAYOUT_UNUSED_0xD: 13,
    LAYOUT_UNUSED_0xE: 14,
    LAYOUT_UNUSED_0xF: 15,
};

export const TerrainType = {
    TERRAIN_WALL: 0,
    TERRAIN_NORMAL: 1,
    TERRAIN_SECONDARY: 2,
    TERRAIN_CHASM: 3,
};

export const SecondaryTerrainType = {
    SECONDARY_TERRAIN_WATER: 0,
    SECONDARY_TERRAIN_LAVA: 1,
    SECONDARY_TERRAIN_CHASM: 2,
};

export const DungeonObjectiveType = {
    OBJECTIVE_STORY: 0,
    OBJECTIVE_NORMAL: 1,
    OBJECTIVE_RESCUE: 2,
    OBJECTIVE_UNK_GAMEMODE_5: 3,
};

export const MissionType = {
    MISSION_RESCUE_CLIENT: 0,
    MISSION_RESCUE_TARGET: 1,
    MISSION_ESCORT_TO_TARGET: 2,
    MISSION_EXPLORE_WITH_CLIENT: 3,
    MISSION_PROSPECT_WITH_CLIENT: 4,
    MISSION_GUIDE_CLIENT: 5,
    MISSION_FIND_ITEM: 6,
    MISSION_DELIVER_ITEM: 7,
    MISSION_SEARCH_FOR_TARGET: 8,
    MISSION_TAKE_ITEM_FROM_OUTLAW: 9,
    MISSION_ARREST_OUTLAW: 10,
    MISSION_CHALLENGE_REQUEST: 11,
    MISSION_TREASURE_MEMO: 12,
};

export const MissionSubtypeChallenge = {
    MISSION_CHALLENGE_NORMAL: 0,
    MISSION_CHALLENGE_MEWTWO: 1,
    MISSION_CHALLENGE_ENTEI: 2,
    MISSION_CHALLENGE_RAIKOU: 3,
    MISSION_CHALLENGE_SUICUNE: 4,
    MISSION_CHALLENGE_JIRACHI: 5,
};

export const MissionSubtypeExplore = {
    MISSION_EXPLORE_NORMAL: 0,
    MISSION_EXPLORE_SEALED_CHAMBER: 1,
    MISSION_EXPLORE_GOLDEN_CHAMBER: 2,
    MISSION_EXPLORE_NEW_DUNGEON: 3,
};

export const MissionSubtypeOutlaw = {
    MISSION_OUTLAW_NORMAL_0: 0,
    MISSION_OUTLAW_NORMAL_1: 1,
    MISSION_OUTLAW_NORMAL_2: 2,
    MISSION_OUTLAW_NORMAL_3: 3,
    MISSION_OUTLAW_ESCORT: 4,
    MISSION_OUTLAW_FLEEING: 5,
    MISSION_OUTLAW_HIDEOUT: 6,
    MISSION_OUTLAW_MONSTER_HOUSE: 7,
};

export const MissionSubtypeTakeItem = {
    MISSION_TAKE_ITEM_NORMAL_OUTLAW: 0,
    MISSION_TAKE_ITEM_HIDDEN_OUTLAW: 1,
    MISSION_TAKE_ITEM_FLEEING_OUTLAW: 2,
};

export const FloorSize = {
    FLOOR_SIZE_LARGE: 0,
    FLOOR_SIZE_SMALL: 1,
    FLOOR_SIZE_MEDIUM: 2,
};

export const HiddenStairsType = {
    HIDDEN_STAIRS_NONE: 0,
    HIDDEN_STAIRS_SECRET_BAZAAR: 1,
    HIDDEN_STAIRS_SECRET_ROOM: 2,
    HIDDEN_STAIRS_RANDOM_SECRET_BAZAAR_OR_SECRET_ROOM: 255,
};

export const FloorType = {
    FLOOR_TYPE_NORMAL: 0,
    FLOOR_TYPE_FIXED: 1,
    FLOOR_TYPE_RESCUE: 2,
};

export const DirectionId = {
    DIR_NONE: 4294967295,
    DIR_DOWN: 0,
    DIR_DOWN_RIGHT: 1,
    DIR_RIGHT: 2,
    DIR_UP_RIGHT: 3,
    DIR_UP: 4,
    DIR_UP_LEFT: 5,
    DIR_LEFT: 6,
    DIR_DOWN_LEFT: 7,
    DIR_CURRENT: 8,
};

export const CardinalDirection = {
    DIR_RIGHT: 0,
    DIR_UP: 1,
    DIR_LEFT: 2,
    DIR_DOWN: 3,
};

export const SecondaryStructureType = {
    SECONDARY_STRUCTURE_NONE: 0,
    SECONDARY_STRUCTURE_MAZE_PLUS_DOT: 1,
    SECONDARY_STRUCTURE_CHECKERBOARD: 2,
    SECONDARY_STRUCTURE_POOL: 3,
    SECONDARY_STRUCTURE_ISLAND: 4,
    SECONDARY_STRUCTURE_DIVIDER: 5,
};

export const GenerationStepLevel = {
    GEN_STEP_COMPLETE: 0,
    GEN_STEP_MAJOR: 1,
    GEN_STEP_MINOR: 2,
};

export const MajorGenerationType = {
    GEN_TYPE_RESET_FLOOR: 0,
    GEN_TYPE_INIT_DUNGEON_GRID: 1,
    GEN_TYPE_CREATE_ROOMS_AND_ANCHORS: 2,
    GEN_TYPE_CREATE_GRID_CELL_CONNECTIONS: 3,
    GEN_TYPE_ENSURE_CONNECTED_GRID: 4,
    GEN_TYPE_GENERATE_MAZE_ROOM: 5,
    GEN_TYPE_GENERATE_KECLEON_SHOP: 6,
    GEN_TYPE_GENERATE_MONSTER_HOUSE: 7,
    GEN_TYPE_GENERATE_EXTRA_HALLWAYS: 8,
    GEN_TYPE_GENERATE_ROOM_IMPERFECTIONS: 9,
    GEN_TYPE_GENERATE_SECONDARY_STRUCTURES: 10,
    GEN_TYPE_ONE_ROOM_MONSTER_HOUSE_FLOOR: 11,
    GEN_TYPE_OUTER_RING_FLOOR: 12,
    GEN_TYPE_CROSSROADS_FLOOR: 13,
    GEN_TYPE_TWO_ROOMS_WITH_MONSTER_HOUSE_FLOOR: 14,
    GEN_TYPE_MERGE_ROOM_VERTICALLY: 15,
    GEN_TYPE_GENERATE_SECONDARY_TERRAIN: 16,
    GEN_TYPE_SPAWN_NON_ENEMIES: 17,
    GEN_TYPE_SPAWN_ENEMIES: 18,
    GEN_TYPE_GENERATE_FLOOR: 19,
};

export const MinorGenerationType = {
    GEN_TYPE_CREATE_ROOM: 0,
    GEN_TYPE_CREATE_ANCHOR: 1,
    GEN_TYPE_CREATE_HALLWAY: 2,
    GEN_TYPE_MERGE_ROOM: 3,
    GEN_TYPE_ENSURE_CONNECTED_HALLWAY: 4,
    GEN_TYPE_REMOVE_UNCONNECTED_ANCHOR: 5,
    GEN_TYPE_REMOVE_UNCONNECTED_ROOM: 6,
    GEN_TYPE_GENERATE_EXTRA_HALLWAY: 7,
    GEN_TYPE_GENERATE_ROOM_IMPERFECTION: 8,
    GEN_TYPE_GENERATE_SECONDARY_STRUCTURE: 9,
    GEN_TYPE_MERGE_ROOM_VERTICALLY: 10,
    GEN_TYPE_SECONDARY_TERRAIN_RIVER: 11,
    GEN_TYPE_SECONDARY_TERRAIN_RIVER_LAKE: 12,
    GEN_TYPE_SECONDARY_TERRAIN_STANDALONE_LAKE: 13,
    GEN_TYPE_SPAWN_STAIRS: 14,
    GEN_TYPE_SPAWN_ITEMS: 15,
    GEN_TYPE_SPAWN_BURIED_ITEMS: 16,
    GEN_TYPE_SPAWN_MONSTER_HOUSE_ITEMS_TRAPS: 17,
    GEN_TYPE_SPAWN_TRAPS: 18,
    GEN_TYPE_SPAWN_PLAYER: 19,
    GEN_TYPE_SPAWN_NON_MONSTER_HOUSE_ENEMIES: 20,
    GEN_TYPE_SPAWN_MONSTER_HOUSE_EXTRA_ENEMIES: 21,
};
